"""init

Revision ID: 14c514c0c12c
Revises: f8096195c19f
Create Date: 2026-04-18 12:15:32.978618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14c514c0c12c'
down_revision: Union[str, Sequence[str], None] = 'f8096195c19f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'business_name',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('it_services', 'healthcare', 'education', 'finance', 'retail', 'real_estate', 'hospitality', 'manufacturing', 'transportation', 'entertainment', 'restaurants', 'salon', name='bussinestype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'business_name',
               existing_type=sa.Enum('it_services', 'healthcare', 'education', 'finance', 'retail', 'real_estate', 'hospitality', 'manufacturing', 'transportation', 'entertainment', 'restaurants', 'salon', name='bussinestype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
import sqlalchemy as sa
from app.utils.enum import bussinesType

def upgrade():
    # enum create karo (important)
    bussiness_enum = sa.Enum(bussinesType, name="bussinestype")
    bussiness_enum.create(op.get_bind(), checkfirst=True)

    # column alter with USING
    op.alter_column(
        'tenants',
        'business_name',
        type_=bussiness_enum,
        postgresql_using="business_name::text::bussinestype"
    )