"""init

Revision ID: 2fd4f71758d8
Revises: 85ff2f83d9ee
Create Date: 2026-04-21 16:56:00.162834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '2fd4f71758d8'
down_revision: Union[str, Sequence[str], None] = '85ff2f83d9ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('agentId', sa.VARCHAR(), nullable=True),
    sa.Column('agentWhatsappNumber', sa.VARCHAR(), nullable=True),
    sa.Column('countryCode', sa.VARCHAR(), nullable=True),
    sa.Column('isAssigned', sa.BOOLEAN(), nullable=True),
    sa.Column('assignedBy', sa.INTEGER(), nullable=True),
    sa.Column('plan_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('isDeleted', sa.BOOLEAN(), nullable=True),
    sa.Column('isBlocked', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['assignedBy'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agentWhatsappNumber')
    )
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('meta_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('isDeleted', sa.BOOLEAN(), nullable=True),
    sa.Column('isBlocked', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
