"""init

Revision ID: 85ff2f83d9ee
Revises: 
Create Date: 2026-04-21 16:28:16.033506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85ff2f83d9ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('agentId', sa.VARCHAR(), nullable=True),
    sa.Column('agentWhatsappNumber', sa.VARCHAR(), nullable=True),
    sa.Column('countryCode', sa.VARCHAR(), nullable=True),
    sa.Column('isAssigned', sa.BOOLEAN(), nullable=True),
    sa.Column('assignedBy', sa.INTEGER(), nullable=True),
    sa.Column('plan_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('isDeleted', sa.BOOLEAN(), nullable=True),
    sa.Column('isBlocked', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['assignedBy'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agentWhatsappNumber')
    )
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    # ### end Alembic commands ###
