"""init

Revision ID: f8096195c19f
Revises: 
Create Date: 2026-04-13 22:49:50.549477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8096195c19f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phoneVerify', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('emailVerify', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('stripe_account_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('dob', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dob')
    op.drop_column('users', 'stripe_account_id')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'emailVerify')
    op.drop_column('users', 'phoneVerify')
    # ### end Alembic commands ###
